/*

 BACKGROUND.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#include <gb/gb.h>
#include "background.h"

/* Background palette data. */
const unsigned short BackgroundPalette[32] = {
  BackgroundCGBPal0c0, BackgroundCGBPal0c1, BackgroundCGBPal0c2, BackgroundCGBPal0c3,
  BackgroundCGBPal1c0, BackgroundCGBPal1c1, BackgroundCGBPal1c2, BackgroundCGBPal1c3,
  BackgroundCGBPal2c0, BackgroundCGBPal2c1, BackgroundCGBPal2c2, BackgroundCGBPal2c3,
  BackgroundCGBPal3c0, BackgroundCGBPal3c1, BackgroundCGBPal3c2, BackgroundCGBPal3c3,
  BackgroundCGBPal4c0, BackgroundCGBPal4c1, BackgroundCGBPal4c2, BackgroundCGBPal4c3,
  BackgroundCGBPal5c0, BackgroundCGBPal5c1, BackgroundCGBPal5c2, BackgroundCGBPal5c3,
  BackgroundCGBPal6c0, BackgroundCGBPal6c1, BackgroundCGBPal6c2, BackgroundCGBPal6c3,
  BackgroundCGBPal7c0, BackgroundCGBPal7c1, BackgroundCGBPal7c2, BackgroundCGBPal7c3
};

/* Start of tile array. */
const unsigned char Background[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of BACKGROUND.C */
