/*

 BACKGROUND.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Background_h_INCLUDE
#define __Background_h_INCLUDE

/* Bank of tiles. */
#define BackgroundBank 0

/* Super Gameboy palette 0 */
#define BackgroundSGBPal0c0 6076
#define BackgroundSGBPal0c1 8935
#define BackgroundSGBPal0c2 6596
#define BackgroundSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BackgroundSGBPal1c0 6076
#define BackgroundSGBPal1c1 8935
#define BackgroundSGBPal1c2 6596
#define BackgroundSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BackgroundSGBPal2c0 6076
#define BackgroundSGBPal2c1 8935
#define BackgroundSGBPal2c2 6596
#define BackgroundSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BackgroundSGBPal3c0 6076
#define BackgroundSGBPal3c1 8935
#define BackgroundSGBPal3c2 6596
#define BackgroundSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BackgroundCGBPal0c0 32544
#define BackgroundCGBPal0c1 5082
#define BackgroundCGBPal0c2 5760
#define BackgroundCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BackgroundCGBPal1c0 32544
#define BackgroundCGBPal1c1 5082
#define BackgroundCGBPal1c2 5760
#define BackgroundCGBPal1c3 0

/* Gameboy Color palette 2 */
#define BackgroundCGBPal2c0 32544
#define BackgroundCGBPal2c1 5082
#define BackgroundCGBPal2c2 5760
#define BackgroundCGBPal2c3 0

/* Gameboy Color palette 3 */
#define BackgroundCGBPal3c0 32544
#define BackgroundCGBPal3c1 5082
#define BackgroundCGBPal3c2 5760
#define BackgroundCGBPal3c3 0

/* Gameboy Color palette 4 */
#define BackgroundCGBPal4c0 32544
#define BackgroundCGBPal4c1 5082
#define BackgroundCGBPal4c2 5760
#define BackgroundCGBPal4c3 0

/* Gameboy Color palette 5 */
#define BackgroundCGBPal5c0 32544
#define BackgroundCGBPal5c1 5082
#define BackgroundCGBPal5c2 5760
#define BackgroundCGBPal5c3 0

/* Gameboy Color palette 6 */
#define BackgroundCGBPal6c0 32544
#define BackgroundCGBPal6c1 5082
#define BackgroundCGBPal6c2 5760
#define BackgroundCGBPal6c3 0

/* Gameboy Color palette 7 */
#define BackgroundCGBPal7c0 32544
#define BackgroundCGBPal7c1 5082
#define BackgroundCGBPal7c2 5760
#define BackgroundCGBPal7c3 0

/* CGB palette entries. */
#define BackgroundCGB0 0

/* Background palette data. */
const unsigned short BackgroundPalette[32] = {
    BackgroundCGBPal0c0, BackgroundCGBPal0c1, BackgroundCGBPal0c2, BackgroundCGBPal0c3,
    BackgroundCGBPal1c0, BackgroundCGBPal1c1, BackgroundCGBPal1c2, BackgroundCGBPal1c3,
    BackgroundCGBPal2c0, BackgroundCGBPal2c1, BackgroundCGBPal2c2, BackgroundCGBPal2c3,
    BackgroundCGBPal3c0, BackgroundCGBPal3c1, BackgroundCGBPal3c2, BackgroundCGBPal3c3,
    BackgroundCGBPal4c0, BackgroundCGBPal4c1, BackgroundCGBPal4c2, BackgroundCGBPal4c3,
    BackgroundCGBPal5c0, BackgroundCGBPal5c1, BackgroundCGBPal5c2, BackgroundCGBPal5c3,
    BackgroundCGBPal6c0, BackgroundCGBPal6c1, BackgroundCGBPal6c2, BackgroundCGBPal6c3,
    BackgroundCGBPal7c0, BackgroundCGBPal7c1, BackgroundCGBPal7c2, BackgroundCGBPal7c3
};

/* Start of tile array. */
extern const unsigned char Background[];

#endif

/* End of BACKGROUND.H */
