/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 65

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Sprites_h_INCLUDE
#define __Sprites_h_INCLUDE

/* Bank of tiles. */
#define SpritesBank 0

/* Super Gameboy palette 0 */
#define SpritesSGBPal0c0 6076
#define SpritesSGBPal0c1 8935
#define SpritesSGBPal0c2 6596
#define SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SpritesSGBPal1c0 6076
#define SpritesSGBPal1c1 8935
#define SpritesSGBPal1c2 6596
#define SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SpritesSGBPal2c0 6076
#define SpritesSGBPal2c1 8935
#define SpritesSGBPal2c2 6596
#define SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SpritesSGBPal3c0 6076
#define SpritesSGBPal3c1 8935
#define SpritesSGBPal3c2 6596
#define SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SpritesCGBPal0c0 32544
#define SpritesCGBPal0c1 927
#define SpritesCGBPal0c2 4447
#define SpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SpritesCGBPal1c0 32544
#define SpritesCGBPal1c1 927
#define SpritesCGBPal1c2 25439
#define SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define SpritesCGBPal2c0 32544
#define SpritesCGBPal2c1 5082
#define SpritesCGBPal2c2 5760
#define SpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define SpritesCGBPal3c0 32544
#define SpritesCGBPal3c1 8834
#define SpritesCGBPal3c2 10271
#define SpritesCGBPal3c3 5136

/* Gameboy Color palette 4 */
#define SpritesCGBPal4c0 32544
#define SpritesCGBPal4c1 5456
#define SpritesCGBPal4c2 10271
#define SpritesCGBPal4c3 5136

/* Gameboy Color palette 5 */
#define SpritesCGBPal5c0 32544
#define SpritesCGBPal5c1 341
#define SpritesCGBPal5c2 6342
#define SpritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define SpritesCGBPal6c0 32544
#define SpritesCGBPal6c1 32650
#define SpritesCGBPal6c2 29491
#define SpritesCGBPal6c3 32767

/* Gameboy Color palette 7 */
#define SpritesCGBPal7c0 32544
#define SpritesCGBPal7c1 32767
#define SpritesCGBPal7c2 12684
#define SpritesCGBPal7c3 0

/* CGB palette entries. */
#define SpritesCGB0 0
#define SpritesCGB1 1
#define SpritesCGB2 0
#define SpritesCGB3 1
#define SpritesCGB4 2
#define SpritesCGB5 2
#define SpritesCGB6 2
#define SpritesCGB7 2
#define SpritesCGB8 4
#define SpritesCGB9 3
#define SpritesCGB10 3
#define SpritesCGB11 3
#define SpritesCGB12 5
#define SpritesCGB13 5
#define SpritesCGB14 5
#define SpritesCGB15 5
#define SpritesCGB16 4
#define SpritesCGB17 0
#define SpritesCGB18 0
#define SpritesCGB19 0
#define SpritesCGB20 0
#define SpritesCGB21 0
#define SpritesCGB22 0
#define SpritesCGB23 0
#define SpritesCGB24 0
#define SpritesCGB25 0
#define SpritesCGB26 0
#define SpritesCGB27 0
#define SpritesCGB28 0
#define SpritesCGB29 0
#define SpritesCGB30 0
#define SpritesCGB31 0
#define SpritesCGB32 0
#define SpritesCGB33 0
#define SpritesCGB34 0
#define SpritesCGB35 0
#define SpritesCGB36 0
#define SpritesCGB37 0
#define SpritesCGB38 0
#define SpritesCGB39 0
#define SpritesCGB40 7
#define SpritesCGB41 7
#define SpritesCGB42 7
#define SpritesCGB43 7
#define SpritesCGB44 7
#define SpritesCGB45 7
#define SpritesCGB46 7
#define SpritesCGB47 6
#define SpritesCGB48 6
#define SpritesCGB49 6
#define SpritesCGB50 6
#define SpritesCGB51 6
#define SpritesCGB52 6
#define SpritesCGB53 6
#define SpritesCGB54 6
#define SpritesCGB55 6
#define SpritesCGB56 6
#define SpritesCGB57 6
#define SpritesCGB58 6
#define SpritesCGB59 6
#define SpritesCGB60 6
#define SpritesCGB61 6
#define SpritesCGB62 6
#define SpritesCGB63 6
#define SpritesCGB64 6
#define SpritesCGB65 6

/* Sprite palette data. */
extern const unsigned short SpritePalette[32];

/* Sprite font entries. */
extern const UINT8 SpriteHeart;
extern const UINT8 SpriteCursor;
extern const UINT8 SpriteNumbers[10];
extern const UINT8 SpriteTextGAMEOVER[8];
extern const UINT8 SpriteTextSTART[5];
extern const UINT8 SpriteTextCHANGE[6];
extern const UINT8 SpriteTextNICE[5];

/* Start of tile array. */
extern const unsigned char Sprites[];

#endif

/* End of SPRITES.H */
