/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Sprites_h_INCLUDE
#define __Sprites_h_INCLUDE

/* Bank of tiles. */
#define SpritesBank 0

/* Super Gameboy palette 0 */
#define SpritesSGBPal0c0 6076
#define SpritesSGBPal0c1 8935
#define SpritesSGBPal0c2 6596
#define SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SpritesSGBPal1c0 6076
#define SpritesSGBPal1c1 8935
#define SpritesSGBPal1c2 6596
#define SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SpritesSGBPal2c0 6076
#define SpritesSGBPal2c1 8935
#define SpritesSGBPal2c2 6596
#define SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SpritesSGBPal3c0 6076
#define SpritesSGBPal3c1 8935
#define SpritesSGBPal3c2 6596
#define SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SpritesCGBPal0c0 32544
#define SpritesCGBPal0c1 927
#define SpritesCGBPal0c2 4447
#define SpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SpritesCGBPal1c0 32544
#define SpritesCGBPal1c1 927
#define SpritesCGBPal1c2 28607
#define SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define SpritesCGBPal2c0 32544
#define SpritesCGBPal2c1 5082
#define SpritesCGBPal2c2 5760
#define SpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define SpritesCGBPal3c0 32544
#define SpritesCGBPal3c1 8834
#define SpritesCGBPal3c2 10271
#define SpritesCGBPal3c3 5136

/* Gameboy Color palette 4 */
#define SpritesCGBPal4c0 32544
#define SpritesCGBPal4c1 5456
#define SpritesCGBPal4c2 10271
#define SpritesCGBPal4c3 5136

/* Gameboy Color palette 5 */
#define SpritesCGBPal5c0 32544
#define SpritesCGBPal5c1 341
#define SpritesCGBPal5c2 6342
#define SpritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define SpritesCGBPal6c0 32544
#define SpritesCGBPal6c1 927
#define SpritesCGBPal6c2 4447
#define SpritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define SpritesCGBPal7c0 32544
#define SpritesCGBPal7c1 927
#define SpritesCGBPal7c2 4447
#define SpritesCGBPal7c3 0

/* CGB palette entries. */
#define SpritesCGB0 0
#define SpritesCGB1 1
#define SpritesCGB2 0
#define SpritesCGB3 1
#define SpritesCGB4 2
#define SpritesCGB5 2
#define SpritesCGB6 2
#define SpritesCGB7 2
#define SpritesCGB8 4
#define SpritesCGB9 3
#define SpritesCGB10 3
#define SpritesCGB11 3
#define SpritesCGB12 5
#define SpritesCGB13 5
#define SpritesCGB14 5
#define SpritesCGB15 5

/* Sprite palette data. */
const palette_color_t SpritePalette[32] = {
    SpritesCGBPal0c0, SpritesCGBPal0c1, SpritesCGBPal0c2, SpritesCGBPal0c3,
    SpritesCGBPal1c0, SpritesCGBPal1c1, SpritesCGBPal1c2, SpritesCGBPal1c3,
    SpritesCGBPal2c0, SpritesCGBPal2c1, SpritesCGBPal2c2, SpritesCGBPal2c3,
    SpritesCGBPal3c0, SpritesCGBPal3c1, SpritesCGBPal3c2, SpritesCGBPal3c3,
    SpritesCGBPal4c0, SpritesCGBPal4c1, SpritesCGBPal4c2, SpritesCGBPal4c3,
    SpritesCGBPal5c0, SpritesCGBPal5c1, SpritesCGBPal5c2, SpritesCGBPal5c3,
    SpritesCGBPal6c0, SpritesCGBPal6c1, SpritesCGBPal6c2, SpritesCGBPal6c3,
    SpritesCGBPal7c0, SpritesCGBPal7c1, SpritesCGBPal7c2, SpritesCGBPal7c3
};

/* Start of tile array. */
extern const unsigned char Sprites[];

#endif

/* End of SPRITES.H */
